BlogLinkText = "Blog"
CAITDescription = "TODO generate text via chat gpt"
CAITImageCaption = "TODO generate text via image generator"
CAITTitle = "data science project"
CoflnetDescription = "TODO generate text via chat gpt"
CoflnetImageCaption = "TODO generate text via image generator"
CoflnetTitle = "Skyblock project was kinda funny"
CompanyDescription = "Coflnet is a company that does stuff"
CompanyName = "Coflnet"
ContactFormDescription = "Please fill out the form below to contact us."
ContactFormEmail = "Email"
ContactFormFirstname = "Firstname"
ContactFormHeader = "Contact form"
ContactFormLastname = "Lastname"
ContactFormMessage = "Message"
ContactFormSendText = "Send"
FDZDescription = "TODO generate text via chat gpt"
FDZImageCaption = "TODO generate text via image generator"
FDZTitle = "fancy research project"
ImprintText = "Imprint"
ThemeSwitchAuto = "Auto"
ThemeSwitchBlack = "Dark"
ThemeSwitchLight = "Light"
ThemeSwitchText = "Theme"
